/*
 * File: app/view/liebiao.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.create('Ext.data.Store',
{
	storeId : 'gongwen',
	fields : ['wenhao', 'biaoti', 'riqi', 'laiwen', 'jingbanren', 'chakan', 'xiazai', 'dayin', 'fuzhi'],
	data :
	{
		'items' : [
			{
				'wenhao' : '湘纪办【2015】1号',
				'biaoti' : '关于组织推荐干部参加省纪委省监察厅公开选调考试的通知',
				'riqi' : '2015-01-12',
				'laiwen' : '省纪委',
				'jingbanren' : '刘赛华',
				'chakan' : '查看',
				'xiazai' : '下载',
				'dayin' : '打印',
				'fuzhi' : '复制'
			}
		]
	},
	proxy :
	{
		type : 'memory',
		reader :
		{
			type : 'json',
			rootProperty : 'items'
		}
	}
}
);
Ext.define('MyApp.view.qd.sort',
{
	extend : 'Ext.panel.Panel',
	alias : 'widget.mypanel3',

	requires : [
		'MyApp.view.qd.sortViewModel',
		'Ext.toolbar.Toolbar',
		'Ext.button.Button',
		'Ext.toolbar.Separator',
		'Ext.form.Panel',
		'Ext.form.field.ComboBox',
		'Ext.form.field.Date',
		'Ext.form.trigger.Spinner',
		'Ext.form.field.Spinner',
		'Ext.grid.Panel',
		'Ext.grid.View',
		'Ext.grid.column.Check'
	],
	viewModel :
	{
		type : 'mypanel3'
	},
	title : '公文列表',
	reference : 'sort',
	dockedItems : [
		{
			xtype : 'toolbar',
			dock : 'top',
			padding : '0 0 1 0',
			style : 'background-color:#F5F5F5; background-image:url();',
			height : 30,
			items : [
				'->',
				{
					xtype : 'button',
					height : 22,
					text : '查找内容',
					listeners:
					{
						click:{
							fn:function(){
								Ext.create('MyApp.view.win.UploadWin').show();
							}
						}
					}
				},
				{
					xtype : 'button',
					height : 22,
					text : '公文借阅'
				},
				{
					xtype : 'button',
					height : 22,
					text : '推送'
				},
				{
					xtype : 'button',
					height : 22,
					margin : '0 10 0 0',
					text : '权限设置'
				}
			]
		},
		{
			xtype : 'pagingtoolbar',
			dock : 'bottom',
			store : Ext.data.StoreManager.lookup('gongwen'),
			displayInfo : true
		}
	],
	items : [
		{
			xtype : 'form',
			bodyStyle : 'background:#F5F5F5;',
			margin : '0 10 10 0',
			header : false,
			border:0,
			region : 'north',
			layout :
			{
				type : 'table',
				columns : 3
			},
			defaults :
			{
				labelWidth : 90,
				labelAlign : 'right',
				margin : '10 0 0 0',
				width : '100%'
			},
			items : [
				{
					xtype : 'textfield',
					margin : '0 0 0 0',
					fieldLabel : '文件标题'
				},
				{
					xtype : 'combobox',
					margin : '0 0 0 0',
					fieldLabel : '文种类型'
				},
				{
					xtype : 'textfield',
					margin : '0 0 0 0',
					fieldLabel : '文&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号',
				},
				{
					xtype : 'textfield',
					fieldLabel : '来文机关',
				},
				{
					xtype : 'textfield',
					fieldLabel : '经&nbsp;&nbsp;&nbsp;办&nbsp;人',
				},
				{
					xtype : 'datefield',
					fieldLabel : '收/发文日期',
					emptyText : '年/月/日',
					format : 'Y/m/d'
				}
			]
		},
		{
			xtype : 'gridpanel',
			title : '公文列表',
			bodyStyle : 'background-color:#F5F5F5',
			enableColumnHide : false,
			forceFit : false,
			sortableColumns : false,
			store : 'gongwen',
			region : 'center',
			selType : 'checkboxmodel',
			// plugins : [
				// {
					// ptype : 'rowediting'
				// }
			// ],
			columns : [
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 140,
					dataIndex : 'wenhao',
					text : '文号'
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					flex : 1,
					minWidth : 200,
					dataIndex : 'biaoti',
					text : '标题'
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 100,
					dataIndex : 'riqi',
					text : '收/发文日期'
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 110,
					dataIndex : 'laiwen',
					text : '来文单位'
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 80,
					dataIndex : 'jingbanren',
					text : '经办人'
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 60,
					dataIndex : 'chakan',
					text : '查看',
					renderer : function (v)
					{
						return '<a href=javascript:click("' + v + '")>' + v + '</a>';
					}
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 60,
					dataIndex : 'xiazai',
					text : '下载',
					renderer : function (v)
					{
						return '<a href=javascript:click("' + v + '")>' + v + '</a>';
					}
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 60,
					dataIndex : 'dayin',
					text : '打印',
					renderer : function (v)
					{
						return '<a href=javascript:click("' + v + '")>' + v + '</a>';
					}
				},
				{
					xtype : 'gridcolumn',
					align : 'center',
					width : 60,
					dataIndex : 'fuzhi',
					text : '复制',
					renderer : function (v)
					{
						return '<a href=javascript:click("' + v + '")>' + v + '</a>';
					}
				}
			]
		}
	]

}
);
var click = function (v)
{
	Ext.Msg.alert('提示','我是' + v);
}
