/*
 * File: app/view/liebiao.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.create('Ext.data.Store',
    {
        storeId: 'sortStore',
        fields: ['id', 'name','post_count'],
        proxy: {
            url: 'admin/sort-list',
            type: 'ajax',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        autoLoad: true
    }
);
Ext.define('MyApp.view.qd.sort',
    {
        extend: 'Ext.panel.Panel',
        alias: 'widget.mypanel3',

        requires: [
            'MyApp.view.qd.sortViewModel',
            'MyApp.view.qd.sortViewController',
            'Ext.toolbar.Toolbar',
            'Ext.button.Button',
            'Ext.toolbar.Separator',
            'Ext.form.Panel',
            'Ext.form.field.ComboBox',
            'Ext.form.field.Date',
            'Ext.form.trigger.Spinner',
            'Ext.form.field.Spinner',
            'Ext.grid.Panel',
            'Ext.grid.View',
            'Ext.grid.column.Check'
        ],
        viewModel: {
            type: 'mypanel3'
        },
        controller: {
            type: 'mycontroller'
        },
        title: '栏目管理',
        reference: 'sort',
        dockedItems: [
            {
                xtype: 'toolbar',
                dock: 'top',
                padding: '0 0 1 0',
                style: 'background-color:#F5F5F5; background-image:url();',
                height: 30,
                items: [
                    '->',
                    {
                        xtype: 'textfield',
                        labelWidth: 60,
                        fieldLabel: '',
                        emptyText: '请输入关键字'
                    },
                    {
                        xtype: 'button',
                        glyph: 0xf002,
                        text: '查找'
                    },
                    {
                        xtype: 'button',
                        glyph: 0xf0fe,
                        reference: 'addBtn',
                        text: '新增',
                        listeners: {
                            click: 'OnaddBtnClick'
                        }
                    },
                    {
                        xtype: 'button',
                        reference: 'editBtn',
                        glyph: 0xf044,
                        text: '编辑',
                        listeners: {
                            click: 'OneditBtnClick'
                        }
                    },
                    {
                        xtype: 'button',
                        reference: 'delBtn',
                        glyph: 0xf1f8,
                        text: '删除',
                        listeners: {
                            click: 'OndelBtnClick'
                        }
                    }
                ]
            },
            {
                xtype: 'pagingtoolbar',
                reference: 'blog_pagingtoolbar',
                store: Ext.data.StoreManager.lookup('sortStore'),
                dock: 'bottom',
                displayInfo: true
            }
        ],
        items: [
            {
                xtype: 'gridpanel',
                reference:'gridpanel',
                bodyStyle: 'background-color:#F5F5F5',
                enableColumnHide: false,
                forceFit: false,
                sortableColumns: true,
                store: Ext.data.StoreManager.lookup('sortStore'),
                region: 'center',
                selType: 'checkboxmodel',
                listeners: {
                    itemdblclick: 'onGridPanelItemdblclick'
                },
                // plugins : [
                // {
                // ptype : 'rowediting'
                // }
                // ],
                columns: [
                    {
                        xtype: 'gridcolumn',
                        align: 'center',
                        width: 60,
                        dataIndex: 'id',
                        text: 'ID'
                    },
                    {
                        xtype: 'gridcolumn',
                        flex: 2,
                        minWidth: 200,
                        dataIndex: 'name',
                        text: '栏目名称'
                    },
                    {
                        xtype: 'gridcolumn',
                        flex: 1,
                        minWidth: 200,
                        dataIndex: 'post_count',
                        text: '文章数'
                    },
                    {
                        xtype: 'gridcolumn',
                        flex: 1,
                        minWidth: 200,
                        dataIndex: 'password',
                        text: '栏目密码'
                    },
                ]
            }
        ]

    }
);

Ext.define('MyApp.view.qd.sort_edit',
    {
        extend: 'Ext.window.Window',
        alias: 'widget.uewin',
        title: '发布文章',
        requires: [
            'MyApp.view.custom.UEditor',
        ],
        modal: true,//maximized:true,
        autoShow: true,
        height: 200,
        glyph: 0xf067,
        width: 500,
        layout: 'fit',
        resizable: false,
        controller: 'mycontroller',
        listeners: {
            show: 'OneditWinShow'
        },
        dockedItems: [
            {
                xtype: 'toolbar',
                items: [
                    '->',
                    {
                        xtype: 'button',
                        reference: 'saveBtn',
                        glyph: 0xf0c7,
                        text: '保存',
                        listeners: {
                            click: {
                                fn: function (btn) {
                                    var win = btn.up('window');
                                    var form = win.down('form');
                                    form.submit({
                                        clientValidation: true,
                                        url: '/admin/sort/update',
                                        success: function (form, action) {
                                            win.close();
                                            Ext.Msg.alert('提示', action.result.msg);
                                        },
                                        failure: function (form, action) {
                                            switch (action.failureType) {
                                                case Ext.form.action.Action.CLIENT_INVALID:
                                                    Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                                                    break;
                                                case Ext.form.action.Action.CONNECT_FAILURE:
                                                    Ext.Msg.alert('Failure', 'Ajax communication failed');
                                                    break;
                                                case Ext.form.action.Action.SERVER_INVALID:
                                                    Ext.Msg.alert('Failure', action.result.msg);
                                            }
                                        }
                                    });
                                }
                            }
                        }
                    },
                    {
                        xtype: 'button',
                        reference: 'closeBtn',
                        glyph: 0xf00d,
                        text: '关闭',
                        listeners: {
                            click: {
                                fn: function (btn) {
                                    btn.up('window').close();
                                }
                            }
                        },
                    }
                ]
            },
        ],
        items: [
            {
                xtype: 'form',
                overflowY: 'auto',
                border: false,
                layout: {
                    type: 'table',
                    columns: 3
                },
                defaults: {
                    labelWidth: 60,
                    width: '99%',
                    margin: '10 0 0 0',
                    labelAlign: 'right',
                    colspan: 1
                },
                items: [
                    {
                        xtype: 'hidden',
                        itemId: 'id',
                        name: 'id'
                    },
                    {
                        xtype: 'hidden',
                        name: '_token',
                        value: "<?php echo csrf_token(); ?>"
                    },
                    {
                        xtype: 'textfield',
                        reference:'name',
                        name: 'name',
                        width: '99%',
                        fieldLabel: '栏目名称',
                        colspan: 3
                    },
                    {
                        xtype: 'textfield',
                        reference:'password',
                        name: 'password',
                        fieldLabel: '密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码'
                    }
                ]
            }

        ]
    }
);